import { z } from 'zod';

const object = shape => z.object(shape).strict();
const path = z.string().min(1).refine(value => !value.includes('\0'), 'Paths cannot contain NUL.').describe('Absolute host path, or a path relative to hostProjectId and optional dataRoot. Hidden files, symlinks, parent paths, runtime files and all extensions are accessible.');
const hostProjectId = z.string().uuid().describe('Independent host project UUID returned by host_project_attach; not a legacy workspace/project ID.');
const source = { path: path.default('.'), hostProjectId: hostProjectId.optional(), dataRoot: z.string().min(1).optional().describe('Named data root in the attached host project, for example recordings or logs.') };
const cursor = z.string().optional().describe('Opaque cursor from this tool with the same path and options. Omit to begin. Live directory changes can shift pagination.');
const hash = z.string().regex(/^[a-f0-9]{64}$/);
const expectedSha256 = hash.nullable().optional().describe('Optional whole-file SHA-256 precondition; null requires a missing path. Omit to allow replacing current content. Checked immediately before replacement; external processes can still race this check.');

export const hostTools = {
  host_project_attach: { target: 'host', method: 'projectAttach', write: true, title: 'Attach an existing host project', description: 'Persist discovery of an existing absolute host directory and optional named data roots. No copy, sandbox, checkout or path allowlist. Same name and paths returns the existing hostProjectId; a conflicting name is rejected unless replace=true. This registry is separate from immutable workspaces.', schema: object({ name: z.string().min(1), path, dataRoots: z.record(z.string().min(1), path).default({}), replace: z.boolean().default(false) }) },
  host_projects_list: { target: 'host', method: 'projectsList', title: 'Discover attached host projects', description: 'Recover this owner’s host projects and named data roots from persistent storage. These paths refer to live files; attachment does not pin a Git revision.', schema: object({ cursor: z.number().int().nonnegative().default(0), limit: z.number().int().min(1).max(200).default(50) }) },
  host_path_info: { target: 'host', method: 'pathInfo', title: 'Inspect a live host path', description: 'Read existence, type, symlink target, size, timestamps and permissions. Follows symlinks; includeSha256 streams the complete file without a file-size ceiling. Does not block concurrent coding jobs.', schema: object({ ...source, includeSha256: z.boolean().default(false) }) },
  host_files_list: { target: 'host', method: 'filesList', title: 'List live host files and directories', description: 'List all names including hidden files and runtime data. Follows directory symlinks by default and avoids ancestry loops. Results are bounded and paginated, not an immutable snapshot. Concurrent jobs remain allowed.', schema: object({ ...source, recursive: z.boolean().default(false), followSymlinks: z.boolean().default(true), cursor, limit: z.number().int().min(1).max(200).default(100) }) },
  host_file_read: { target: 'host', method: 'fileRead', title: 'Read any live host file in chunks', description: 'Read a bounded byte page from a file of any size. UTF-8 pages avoid splitting valid characters; use base64 for exact arbitrary bytes. A cursor is a byte offset. includeSha256 streams the whole file; expectedSha256 can detect content changes between pages. Content is returned without redaction and never copied into diagnostic logs.', schema: object({ ...source, cursor: z.number().int().nonnegative().default(0), maxBytes: z.number().int().min(4).max(262144).default(16384), encoding: z.enum(['utf8', 'base64']).default('utf8'), includeSha256: z.boolean().default(false), expectedSha256: hash.optional() }) },
  host_file_write: { target: 'host', method: 'fileWrite', write: true, destructive: true, title: 'Write a live host file', description: 'Replace a file with UTF-8 text or base64 bytes, following its symlink target. Uses a temporary sibling and atomic rename for regular files, preserving existing mode and ownership. mode=append supports large uploads in chunks; optional offset is required to match current size, preventing accidental duplicate appends. Special files use direct writes. No content is logged. There is no file-size ceiling; request transport still has its own message budget.', schema: object({ ...source, content: z.string(), encoding: z.enum(['utf8', 'base64']).default('utf8'), mode: z.enum(['replace', 'append']).default('replace'), offset: z.number().int().nonnegative().optional().describe('Append precondition: current file size must equal this byte offset. Replacement does not accept offset.'), expectedSha256, createParents: z.boolean().default(false), permissions: z.number().int().min(0).max(0o7777).optional().describe('Optional numeric Unix permissions; otherwise preserve existing permissions or create with 0600.') }) },
  host_file_patch: { target: 'host', method: 'filePatch', write: true, destructive: true, title: 'Patch exact text in a live host file', description: 'Replace exactly one occurrence of oldText using a streamed search and atomic replacement, without a file-size ceiling. Follows symlinks and preserves existing mode/ownership. Refuses missing or ambiguous matches and optional stale hashes; no partial edit occurs on these errors. External processes are not locked.', schema: object({ ...source, oldText: z.string().min(1), newText: z.string(), expectedSha256: hash.optional() }) },
  host_search: { target: 'host', method: 'search', title: 'Search live host files of any type', description: 'Search a literal UTF-8 byte sequence across live files, including hidden files, logs, transcripts, credentials and binary data. Follows directory symlinks by default, avoiding ancestry loops. Returns byte offsets and bounded excerpts. Paginated byte/file budgets bound work even when there are no matches. No filename filters or file-size ceiling. Search is case-sensitive; live mutations can shift cursors.', schema: object({ ...source, query: z.string().min(1), recursive: z.boolean().default(true), followSymlinks: z.boolean().default(true), cursor, limit: z.number().int().min(1).max(200).default(50), maxScanBytes: z.number().int().min(1).max(134217728).default(8388608), maxFiles: z.number().int().min(1).max(1000).default(200) }) }
};
