import { z } from 'zod';

const id = z.string().uuid().describe('Persisted UUID returned by Praxis; recover the existing identifier rather than creating a replacement.');
const projectId = z.string().regex(/^[a-z0-9][a-z0-9_-]{0,63}$/).describe('Registered project identifier from projects_list.');
const revision = z.string().min(1).max(128).describe('Exact revision returned by Praxis. Use the current workspace revision for edit or job preconditions.');
const hash = z.string().regex(/^[a-f0-9]{64}$/).describe('Original file SHA-256 returned by file_read, before any changes in this batch.');
const key = z.string().min(8).max(128).regex(/^[A-Za-z0-9._:-]+$/).describe('Durable idempotency key, 8–128 letters, digits, dots, underscores, colons, or hyphens. Preserve the key and identical inputs after an uncertain response.');
const path = z.string().min(1).max(512).describe('Source-relative POSIX path, 1–512 characters; no absolute paths, traversal, or protected runtime files.');
const cursor = z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER).default(0).describe('Omit to begin. Treat nextCursor as opaque: copy the returned value exactly, without adding the number of rows or bytes. Stop when hasMore=false or nextCursor=null.');
const pageSize = (unit, maximum, fallback, minimum = 1) => z.number().int().min(minimum).max(maximum).default(fallback).describe(`Maximum ${unit} per page: ${minimum}–${maximum}; default ${fallback}. Omit for the recommended default. A page may contain fewer ${unit}; follow its returned cursor.`);
const page = pageSize('records', 100, 20);
const diffBytes = z.number().int().min(256).max(32768).describe('Maximum UTF-8 diff bytes per page: 256–32768; default 16384 when both maxBytes and limit are omitted. Omit for the recommended default.');
const source = { projectId: projectId.optional(), workspaceId: id.optional() };
const object = shape => z.object(shape).strict();
const change = z.discriminatedUnion('action', [
  object({ action: z.literal('write'), path, expectedSha256: hash.nullable().describe('Original file hash, or null to create a file that does not exist.'), content: z.string().max(131072).describe('Complete UTF-8 source text, at most 131072 JavaScript string characters. For an existing larger file, use exact-text patches.'), executable: z.boolean().optional() }),
  object({ action: z.literal('patch'), path, expectedSha256: hash, oldText: z.string().min(1).max(131072).describe('Exact nonempty text to replace, at most 131072 characters; must occur once in the text staged by earlier patches in this batch.'), newText: z.string().max(131072).describe('Replacement text, at most 131072 characters. The resulting file may exceed this patch-text limit, within the file byte limit.') }),
  object({ action: z.literal('rename'), path, to: path, expectedSha256: hash }),
  object({ action: z.literal('delete'), path, expectedSha256: hash })
]);

// Both adapters validate these schemas. Authentication identity is never an argument.
export const codeTools = {
  capabilities: { method: null, title: 'Inspect Praxis coding capabilities', description: 'Start here. Read the installed release, isolated coding workflow, precise limits, recovery instructions, and disabled capabilities.', schema: object({}) },
  projects_list: { method: 'projectsList', title: 'Discover registered projects', description: 'List immutable source snapshots registered for this owner, their exact commits, and validation commands. No live checkout is edited.', schema: object({}) },
  project_inspect: { method: 'projectInspect', title: 'Inspect a project snapshot', description: 'Read a registered source snapshot, its exact base revision, repository information, and applicable instructions.', schema: object({ projectId }) },
  files_list: { method: 'filesList', title: 'List source files', description: 'List bounded source paths. Supply exactly one of projectId or workspaceId. Omit pagination arguments initially, then copy nextCursor exactly; excluded runtime directories and credentials are not returned.', schema: object({ ...source, path: z.string().max(512).default('').describe('Optional source-relative directory prefix; empty means all source files.'), cursor, limit: pageSize('file paths', 200, 100) }) },
  file_read: { method: 'read', title: 'Read source with a content hash', description: 'Read numbered source lines from exactly one projectId or workspaceId. Returns a SHA-256 for edit preconditions and a workspace revision where applicable. Omit lineCount for 100 lines (maximum 200). For continuation, copy nextPosition.line to startLine and nextPosition.column to startColumn.', schema: object({ ...source, path, startLine: z.number().int().min(1).max(1000000).default(1).describe('One-based source line, 1–1000000; default 1. Copy nextPosition.line when continuing.'), startColumn: z.number().int().min(1).max(2097152).default(1).describe('One-based UTF-16 code-unit column, 1–2097152; default 1. Copy nextPosition.column for long-line continuation.'), lineCount: pageSize('source lines', 200, 100) }) },
  code_search: { method: 'search', title: 'Search source text', description: 'Search a literal string in exactly one projectId or workspaceId. Results include paths and line numbers with pagination. This is not a regular expression. Omit pagination arguments initially.', schema: object({ ...source, query: z.string().min(1).max(256).describe('Literal text, 1–256 characters; regular expressions are not interpreted.'), path: z.string().max(512).default('').describe('Optional source-relative path prefix; empty searches all source files.'), caseSensitive: z.boolean().default(true).describe('Match case exactly by default; false ignores case.'), cursor, limit: pageSize('matches', 100, 50) }) },
  workspace_create: { method: 'create', write: true, title: 'Create an isolated coding workspace', description: 'Copy a registered immutable source snapshot at baseRevision into a disposable workspace. Save the returned workspaceId. Repeat identical inputs and idempotencyKey after an uncertain response.', schema: object({ projectId, baseRevision: revision, idempotencyKey: key, label: z.string().max(80).default('') }) },
  workspaces_list: { method: 'list', title: 'Recover coding workspaces', description: 'List your persisted workspaces, newest first. Use this in a fresh conversation to find existing work instead of recreating it.', schema: object({ cursor, limit: page }) },
  workspace_inspect: { method: 'inspect', title: 'Inspect workspace state', description: 'Recover the workspace base, current revision, changed files, instructions, and job associations.', schema: object({ workspaceId: id }) },
  workspace_apply: { method: 'apply', write: true, destructive: true, title: 'Apply source edits with preconditions', description: 'Apply an atomic batch to an idle workspace using its current expectedRevision. Exact-text patches work on large files. Multiple patches to one file run in order, all using the ORIGINAL file SHA-256; each oldText must occur once in the text staged so far. Other actions cannot share that path in the batch. Write with expectedSha256=null creates a file. Preserve idempotencyKey and inputs after uncertainty; stale content is rejected.', schema: object({ workspaceId: id, expectedRevision: revision, idempotencyKey: key, changes: z.array(change).min(1).max(32).describe('1–32 edits, applied atomically. Multiple patches per file use the original hash and sequential staged text. Mixed actions on the same path are rejected.') }) },
  workspace_diff: { method: 'diff', title: 'Review the workspace diff', description: 'Read a paginated diff against the immutable base, including new/deleted files and mode changes. Pin expectedRevision across pages. Omit page size for 16384 bytes; maxBytes is the preferred byte-budget field. Legacy limit remains accepted (also bytes, minimum 256). Copy returned nextCursor exactly.', schema: object({ workspaceId: id, expectedRevision: revision.optional(), cursor, maxBytes: diffBytes.optional(), limit: diffBytes.optional().describe('Legacy alias for maxBytes, in UTF-8 bytes, 256–32768. Prefer maxBytes or omit both for 16384. If both are supplied, their values must match.') }).superRefine((args, ctx) => { if (args.maxBytes !== undefined && args.limit !== undefined && args.maxBytes !== args.limit) ctx.addIssue({ code: 'custom', path: ['maxBytes'], message: 'maxBytes and limit must match when both are supplied.' }); }) },
  workspace_remove: { method: 'remove', write: true, destructive: true, title: 'Preview or remove a disposable workspace', description: 'Preview removal by default. To remove, set preview=false with expectedRevision and idempotencyKey. Dirty work additionally requires discard=true. Active jobs prevent removal; stored operation and job receipts remain.', schema: object({ workspaceId: id, expectedRevision: revision, preview: z.boolean().default(true), discard: z.boolean().default(false), idempotencyKey: key.optional() }) },
  operations_list: { method: 'operationsList', title: 'Recover mutation receipts', description: 'List persisted workspace mutation receipts, optionally for one workspace. Inspect these after uncertain responses.', schema: object({ workspaceId: id.optional(), cursor, limit: page }) },
  operation_read: { method: 'operationRead', title: 'Read a mutation receipt', description: 'Read the recorded outcome of an identified mutation without repeating it.', schema: object({ operationId: id }) },
  job_start: { target: 'jobs', method: 'start', write: true, destructive: true, title: 'Run a sandboxed coding command', description: 'Queue argv in one isolated workspace at expectedRevision. Returns a durable job ID promptly. Start with job_status for a compact outcome and recent output; use job_logs for selected detail. Network is disabled. One active job is shared across workspaces; on ACTIVE_JOB_LIMIT observe the existing active job before retrying. Optional artifactPaths preserve files after completion. Retry uncertain submissions with identical inputs and the SAME idempotencyKey.', schema: object({ workspaceId: id, expectedRevision: revision, idempotencyKey: key, label: z.string().max(80).default('').describe('Optional job label, at most 80 characters.'), argv: z.array(z.string().max(8192)).min(1).max(64).describe('Command and arguments as 1–64 strings, at most 8192 characters each and 32768 serialized bytes total. No implicit shell.'), cwd: z.string().max(512).default('.').describe('Workspace-relative working directory; default workspace root (.).'), env: z.partialRecord(z.enum(['CI', 'NODE_ENV', 'TZ', 'LANG', 'LC_ALL', 'FORCE_COLOR', 'NO_COLOR', 'PYTHONHASHSEED', 'PYTHONDONTWRITEBYTECODE']), z.string().max(1000)).default({}).describe('Optional overrides of the listed nonsecret environment variables only; each value at most 1000 characters.'), timeoutSeconds: z.number().int().min(1).max(900).default(300).describe('Execution deadline in seconds: 1–900; default 300. Job execution is independent of this request.'), artifactPaths: z.array(path).max(16).default([]).describe('Up to 16 workspace-relative files to preserve after completion; default none.') }) },
  jobs_list: { target: 'jobs', method: 'list', title: 'Recover coding jobs', description: 'List persisted coding jobs, optionally for a workspace. Completed or interrupted commands are never automatically rerun.', schema: object({ workspaceId: id.optional(), cursor, limit: page }) },
  job_status: { target: 'jobs', method: 'get', title: 'Read coding job status', description: 'Start here to inspect a job: timestamps, exit status, resulting revision, compact command, recent output, and retention facts. Recent output is an excerpt, not a complete log or parsed test verdict. Request includeCommand only when full argv is needed.', schema: object({ jobId: id, includeCommand: z.boolean().default(false).describe('Default false abbreviates argv to keep status compact. Set true to recover the full saved command arguments.') }) },
  job_logs: { target: 'jobs', method: 'logs', title: 'Read bounded command output', description: 'Read retained output with explicit truncation. Default head preserves ordered output and lifecycle records. Use view=tail to see the newest retained output first, or query/stream to narrow either view. Search covers retained records only. Exhaustive log pagination is usually unnecessary for an outcome already shown by job_status.', schema: object({ jobId: id, cursor: cursor.describe('Omit/0 starts the selected view. Copy nextCursor exactly with the same view and filters. Head pages advance forward. Tail starts newest and pages backward, with records inside each page chronological; its sequence namespace is independent of head. Stop when hasMore=false.'), limit: pageSize('log records', 100, 50), view: z.enum(['head', 'tail']).default('head').describe('Default head reads the original retained log and lifecycle records. Tail reads rolling recent output, newest page first; older jobs may not have a retained tail.'), query: z.string().min(1).max(200).optional().describe('Optional case-sensitive literal substring, 1–200 characters; no regex. Matches only records retained in the selected view, not omitted output.'), stream: z.enum(['stdout', 'stderr', 'system']).optional().describe('Optional exact stream filter; omit for all streams. Lifecycle records use system in the head view.') }) },
  job_cancel: { target: 'jobs', method: 'cancel', write: true, destructive: true, title: 'Cancel a coding job', description: 'Request cancellation of an existing command. The worker records its actual outcome; terminal jobs stay terminal.', schema: object({ jobId: id }) },
  artifact_list: { target: 'jobs', method: 'artifactList', title: 'List preserved job artifacts', description: 'List files copied into protected result storage after the job ended, including sizes and hashes.', schema: object({ jobId: id }) },
  artifact_read: { target: 'jobs', method: 'artifactRead', title: 'Read a preserved artifact', description: 'Read a bounded page of a preserved artifact by its identifier. Source access is authenticated and independent of the original chat. Omit limit for 16384 bytes; copy returned nextCursor.', schema: object({ jobId: id, artifactId: z.string().min(1).max(128).describe('Exact artifact identifier returned by artifact_list; this identifier is not necessarily the content hash.'), cursor, limit: pageSize('artifact bytes', 32768, 16384) }) }
};

// Zod messages can contain arbitrary unknown property names. Return only schema
// field names and bounded, value-free issues, never submitted source or values.
export function parseArguments(schema, args) {
  const parsed = schema.safeParse(args);
  if (parsed.success) return parsed.data;
  const fields = new Set([...Object.keys(schema.shape || {}), 'action', 'path', 'expectedSha256', 'content', 'executable', 'oldText', 'newText', 'to']);
  const issues = parsed.error.issues.slice(0, 5).map(issue => {
    const field = issue.path.map(part => typeof part === 'number' && Number.isSafeInteger(part) ? part : fields.has(part) ? part : '<field>').join('.') || '<arguments>';
    const details = issue.code === 'too_small' ? { minimum: issue.minimum } : issue.code === 'too_big' ? { maximum: issue.maximum } : {};
    const message = issue.code === 'too_small' ? `Must be at least ${issue.minimum}.` : issue.code === 'too_big' ? `Must be at most ${issue.maximum}.`
      : issue.code === 'unrecognized_keys' ? 'Contains unsupported fields; use only the advertised arguments.'
        : issue.code === 'invalid_type' ? 'Missing or incorrect argument type.' : issue.code === 'invalid_value' ? 'Value is not one of the advertised options.'
          : issue.code === 'custom' && field === 'maxBytes' ? 'maxBytes and limit must match when both are supplied.'
            : issue.code === 'custom' ? 'Arguments conflict with the documented field constraints.' : 'Value does not match the advertised format.';
    return { field, code: issue.code, message, ...details };
  });
  throw Object.assign(new Error(`Invalid tool arguments: ${issues.map(issue => `${issue.field}: ${issue.message}`).join('; ').slice(0, 500)}`), { code: 'INVALID_ARGUMENT', issues });
}

export function parseCodeCall(action, args) {
  const tool = typeof action === 'string' && Object.hasOwn(codeTools, action) ? codeTools[action] : undefined;
  if (!tool) throw Object.assign(new Error('Unknown coding action'), { code: 'UNKNOWN_ACTION' });
  return { tool, args: parseArguments(tool.schema, args) };
}
