import { z } from 'zod';
import { hostTools } from './host-schema.js';

const id = z.string().uuid().describe('Persisted UUID returned by Praxis; recover the existing identifier rather than creating a replacement.');
const projectId = z.string().regex(/^[a-z0-9][a-z0-9_-]{0,63}$/).describe('Registered project identifier from projects_list.');
const revision = z.string().min(1).max(128).describe('Exact revision returned by Praxis. Use the current workspace revision for edit or job preconditions.');
const hash = z.string().regex(/^[a-f0-9]{64}$/).describe('Original file SHA-256 returned by file_read, before any changes in this batch.');
const key = z.string().min(8).max(128).regex(/^[A-Za-z0-9._:-]+$/).describe('Durable idempotency key, 8–128 letters, digits, dots, underscores, colons, or hyphens. Preserve the key and identical inputs after an uncertain response.');
const path = z.string().min(1).max(512).describe('Source-relative POSIX path, 1–512 characters; no absolute paths, traversal, or protected runtime files.');
const cursor = z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER).default(0).describe('Omit to begin. Treat nextCursor as opaque: copy the returned value exactly, without adding the number of rows or bytes. Stop when hasMore=false or nextCursor=null.');
const pageSize = (unit, maximum, fallback, minimum = 1) => z.number().int().min(minimum).max(maximum).default(fallback).describe(`Maximum ${unit} per page: ${minimum}–${maximum}; default ${fallback}. Omit for the recommended default. A page may contain fewer ${unit}; follow its returned cursor.`);
const page = pageSize('records', 100, 20);
const diffBytes = z.number().int().min(256).max(32768).describe('Maximum UTF-8 diff bytes per page: 256–32768; default 16384 when both maxBytes and limit are omitted. Omit for the recommended default.');
const source = { projectId: projectId.optional(), workspaceId: id.optional() };
const object = shape => z.object(shape).strict();
const change = z.discriminatedUnion('action', [
  object({ action: z.literal('write'), path, expectedSha256: hash.nullable().describe('Original file hash, or null to create a file that does not exist.'), content: z.string().max(131072).describe('Complete UTF-8 source text, at most 131072 JavaScript string characters. For an existing larger file, use exact-text patches.'), executable: z.boolean().optional() }),
  object({ action: z.literal('patch'), path, expectedSha256: hash, oldText: z.string().min(1).max(131072).describe('Exact nonempty text to replace, at most 131072 characters; must occur once in the text staged by earlier patches in this batch.'), newText: z.string().max(131072).describe('Replacement text, at most 131072 characters. The resulting file may exceed this patch-text limit, within the file byte limit.') }),
  object({ action: z.literal('rename'), path, to: path, expectedSha256: hash }),
  object({ action: z.literal('delete'), path, expectedSha256: hash })
]);

// Both adapters validate these schemas. Authentication identity is never an argument.
export const codeTools = {
  project_create: { target: 'git', method: 'projectCreate', write: true, title: 'Create a new isolated project', description: 'Create a real initial Git commit and immutable source snapshot from a node, python, or static scaffold. No GitHub credential is needed for local coding. Names are lowercase words with hyphens, up to 40 characters; project IDs are scoped to the authenticated owner. Returns a durable operationId; read git_operation_status until completed, then project_inspect and workspace_create. Recover existing operations after uncertainty.', schema: object({ name: z.string().regex(/^[a-z][a-z0-9-]{0,39}$/).describe('New project and eventual GitHub repository name, up to 40 lowercase letters, digits, or hyphens; begin with a letter.'), template: z.enum(['node', 'python', 'static']).default('node').describe('Dependency-free starter: Node HTTP server, Python HTTP server, or static site. Each includes an offline validation command.'), idempotencyKey: key }) },
  project_publish: { target: 'git', method: 'projectPublish', write: true, title: 'Create a GitHub repository and publish main', description: 'Publish an owner-created local project to a new repository in the configured GitHub account. Private by default; select public only when the user asks. Pass a completed local commitOperationId to publish built work, or omit to publish the initial scaffold. A protected provisioner creates the repository and a dedicated deploy key, then publishes exact main. Existing repositories are never adopted. Returns a durable operationId; recover it through git_operation_status after uncertainty. Later updates use git_commit/git_push. Requires configured GitHub provisioning authorization.', schema: object({ projectId, visibility: z.enum(['private', 'public']).default('private'), commitOperationId: id.optional().describe('Completed git_commit operation for this project; omit to publish its initial scaffold.'), idempotencyKey: key }) },
  project_sync: { target: 'git', method: 'sync', write: true, title: 'Sync source from GitHub main', description: 'Fetch the registered repository main into a new immutable snapshot. Returns a durable operationId; read git_operation_status until completed before project_inspect or workspace_create. Existing workspaces keep their original bases. Preserve identical inputs and key after uncertainty.', schema: object({ projectId, idempotencyKey: key }) },
  git_commit: { target: 'git', method: 'commit', write: true, title: 'Commit an exact workspace snapshot', description: 'Capture the idle workspace at expectedRevision and create a real Git commit in protected storage. Review the diff and validation outcomes first. Returns a durable operationId; poll git_operation_status. Subsequent commits use this workspace’s last completed commit as parent. Does not push until git_push.', schema: object({ workspaceId: id, expectedRevision: revision, message: z.string().min(1).max(2000).describe('Git commit message explaining the completed change; 1–2000 characters.'), idempotencyKey: key }) },
  git_push: { target: 'git', method: 'push', write: true, title: 'Push a committed change to main', description: 'Publish a completed git_commit operation to the registered GitHub repository main. Requires unchanged expected remote head and fast-forward ancestry. Returns a durable operationId. Recover it through git_operation_status after uncertainty; never create another operation to repeat an ambiguous push.', schema: object({ commitOperationId: id, idempotencyKey: key }) },
  deployment_status: { target: 'git', method: 'deploymentStatus', title: 'Inspect the deployed checkout and service', description: 'Read the registered podcast-discord or owner-created app deployment HEAD and managed-service status. Use its current HEAD as expectedHead for the next deployment. Process status does not establish live application functionality.', schema: object({ projectId }) },
  deployment_fast_forward: { target: 'git', method: 'deploy', write: true, destructive: true, title: 'Fast-forward and restart the podcast deployment', description: 'Deploy the exact commit from a completed git_push operation to the fixed podcast-discord checkout and restart its service. Requires clean checkout, expectedHead, fast-forward ancestry and target equal to GitHub main. Changed package manifests require preparedDependenciesId from successful dependency_prepare with matching manifests and runtime. Recover the durable operation after uncertainty; never repeat an ambiguous restart.', schema: object({ pushOperationId: id, expectedHead: z.string().regex(/^[a-f0-9]{40}$/).describe('Exact deployed Git HEAD from deployment_status, used to detect concurrent changes.'), preparedDependenciesId: hash.optional().describe('Sealed npm dependency bundle from dependency_prepare; required when package manifests change.'), idempotencyKey: key }) },
  production_diagnosis: { target: 'git', method: 'diagnosis', title: 'Inspect production health and operational logs', description: 'Read registered service state and bounded operational events. For complete raw logs, transcripts, recordings and provider results use host_projects_list and host_file_read/host_search; these have no content redaction. Distinguishes a stable process, observed Discord login, and live functionality that has not been verified. Does not send Discord messages or invoke providers.', schema: object({ projectId, limit: z.number().int().min(1).max(100).default(40) }) },
  deployment_history: { target: 'git', method: 'deploymentHistory', title: 'Read deployment and recovery history', description: 'List persisted exact revisions, activation outcomes and recovery journals. Follow the supplied cursor. A previous commit does not imply database or external-effect rollback.', schema: object({ projectId, cursor: id.optional(), limit: z.number().int().min(1).max(100).default(20) }) },
  production_restart: { target: 'git', method: 'restart', write: true, destructive: true, title: 'Recover the registered production service', description: 'Restart only the registered service at its expected deployed HEAD. Returns a durable Git operation. If resolving a previous uncertain restart, explicitly supply recoverOperationId after reviewing its current service observations; the old outcome remains uncertain in history.', schema: object({ projectId, expectedHead: z.string().regex(/^[a-f0-9]{40}$/), recoverOperationId: id.optional(), idempotencyKey: key }) },
  deployment_rollback: { target: 'git', method: 'rollback', write: true, destructive: true, title: 'Restore a recorded application deployment', description: 'Restore the prior source and retained dependency tree from the identified deployment record, requiring expected current HEAD. Restarts the fixed service, preserves runtime data and leaves GitHub history unchanged. Does not undo database migrations or external effects. Recover the returned operation rather than repeating an uncertain activation.', schema: object({ projectId, expectedHead: z.string().regex(/^[a-f0-9]{40}$/), deploymentOperationId: id, recoverOperationId: id.optional(), idempotencyKey: key }) },
  project_deploy: { target: 'git', method: 'projectDeploy', write: true, destructive: true, title: 'Deploy a new project as an isolated web service', description: 'Deploy exact published main for an owner-created Node/Python/static project as an unprivileged stateless HTTP service on the separate apps origin. Set expectedHead=null for first deployment; otherwise use deployment_status. Optional preparedDependenciesId installs matching npm dependencies. To replace a failed or uncertain activation after diagnosis, explicitly reference recoverOperationId. Runtime temp space is bounded; persistent application storage is not provided by this adapter.', schema: object({ publicationOperationId: id, expectedHead: z.string().regex(/^[a-f0-9]{40}$/).nullable(), preparedDependenciesId: hash.optional(), recoverOperationId: id.optional(), idempotencyKey: key }) },
  git_operation_status: { target: 'git', method: 'get', title: 'Recover project, Git, or deployment operations', description: 'Read and reconcile a persisted Git operation, including project creation and first publication. Completion includes exact Git commits and revision provenance. Sync and project creation install immutable snapshots; commit completion records the next parent. Uncertain publication or activation is never blindly repeated.', schema: object({ operationId: id }) },
  git_operations_list: { target: 'git', method: 'list', title: 'Find existing publication operations', description: 'Recover operation IDs in a fresh conversation, optionally for a workspace. Use git_operation_status to refresh nonterminal results before doing more work.', schema: object({ workspaceId: id.optional(), cursor, limit: page }) },
  capabilities: { method: null, title: 'Inspect Praxis coding capabilities', description: 'Start here. Read the installed release, native root execution, host project/file access and durable recovery instructions.', schema: object({}) },
  projects_list: { method: 'projectsList', title: 'Discover registered projects', description: 'List immutable source snapshots registered for this owner, their exact commits, and validation commands. No live checkout is edited.', schema: object({}) },
  project_inspect: { method: 'projectInspect', title: 'Inspect a project snapshot', description: 'Read a registered source snapshot, its exact base revision, repository information, and applicable instructions.', schema: object({ projectId }) },
  files_list: { method: 'filesList', title: 'List source files', description: 'List bounded source paths. Supply exactly one of projectId or workspaceId. Omit pagination arguments initially, then copy nextCursor exactly; excluded runtime directories and credentials are not returned.', schema: object({ ...source, path: z.string().max(512).default('').describe('Optional source-relative directory prefix; empty means all source files.'), cursor, limit: pageSize('file paths', 200, 100) }) },
  file_read: { method: 'read', title: 'Read source with a content hash', description: 'Read numbered source lines from exactly one projectId or workspaceId. Returns a SHA-256 for edit preconditions and a workspace revision where applicable. Omit lineCount for 100 lines (maximum 200). For continuation, copy nextPosition.line to startLine and nextPosition.column to startColumn.', schema: object({ ...source, path, startLine: z.number().int().min(1).max(1000000).default(1).describe('One-based source line, 1–1000000; default 1. Copy nextPosition.line when continuing.'), startColumn: z.number().int().min(1).max(2097152).default(1).describe('One-based UTF-16 code-unit column, 1–2097152; default 1. Copy nextPosition.column for long-line continuation.'), lineCount: pageSize('source lines', 200, 100) }) },
  code_search: { method: 'search', title: 'Search source text', description: 'Search a literal string in exactly one projectId or workspaceId. Results include paths and line numbers with pagination. This is not a regular expression. Omit pagination arguments initially.', schema: object({ ...source, query: z.string().min(1).max(256).describe('Literal text, 1–256 characters; regular expressions are not interpreted.'), path: z.string().max(512).default('').describe('Optional source-relative path prefix; empty searches all source files.'), caseSensitive: z.boolean().default(true).describe('Match case exactly by default; false ignores case.'), cursor, limit: pageSize('matches', 100, 50) }) },
  workspace_create: { method: 'create', write: true, title: 'Create an isolated coding workspace', description: 'Copy a registered immutable source snapshot at baseRevision into a disposable workspace. Save the returned workspaceId. Repeat identical inputs and idempotencyKey after an uncertain response.', schema: object({ projectId, baseRevision: revision, idempotencyKey: key, label: z.string().max(80).default('') }) },
  workspaces_list: { method: 'list', title: 'Recover coding workspaces', description: 'List your persisted workspaces, newest first. Use this in a fresh conversation to find existing work instead of recreating it.', schema: object({ cursor, limit: page }) },
  workspace_inspect: { method: 'inspect', title: 'Inspect workspace state', description: 'Recover the workspace base, current revision, changed files, instructions, and job associations.', schema: object({ workspaceId: id }) },
  workspace_apply: { method: 'apply', write: true, destructive: true, title: 'Apply source edits with preconditions', description: 'Apply an atomic batch to an idle workspace using its current expectedRevision. Exact-text patches work on large files. Multiple patches to one file run in order, all using the ORIGINAL file SHA-256; each oldText must occur once in the text staged so far. Other actions cannot share that path in the batch. Write with expectedSha256=null creates a file. Preserve idempotencyKey and inputs after uncertainty; stale content is rejected.', schema: object({ workspaceId: id, expectedRevision: revision, idempotencyKey: key, changes: z.array(change).min(1).max(32).describe('1–32 edits, applied atomically. Multiple patches per file use the original hash and sequential staged text. Mixed actions on the same path are rejected.') }) },
  workspace_diff: { method: 'diff', title: 'Review the workspace diff', description: 'Read a paginated diff against the immutable base, including new/deleted files and mode changes. Pin expectedRevision across pages. Omit page size for 16384 bytes; maxBytes is the preferred byte-budget field. Legacy limit remains accepted (also bytes, minimum 256). Copy returned nextCursor exactly.', schema: object({ workspaceId: id, expectedRevision: revision.optional(), cursor, maxBytes: diffBytes.optional(), limit: diffBytes.optional().describe('Legacy alias for maxBytes, in UTF-8 bytes, 256–32768. Prefer maxBytes or omit both for 16384. If both are supplied, their values must match.') }).superRefine((args, ctx) => { if (args.maxBytes !== undefined && args.limit !== undefined && args.maxBytes !== args.limit) ctx.addIssue({ code: 'custom', path: ['maxBytes'], message: 'maxBytes and limit must match when both are supplied.' }); }) },
  workspace_remove: { method: 'remove', write: true, destructive: true, title: 'Preview or remove a disposable workspace', description: 'Preview removal by default. To remove, set preview=false with expectedRevision and idempotencyKey. Dirty work additionally requires discard=true. Active jobs prevent removal; stored operation and job receipts remain.', schema: object({ workspaceId: id, expectedRevision: revision, preview: z.boolean().default(true), discard: z.boolean().default(false), idempotencyKey: key.optional() }) },
  operations_list: { method: 'operationsList', title: 'Recover mutation receipts', description: 'List persisted workspace mutation receipts, optionally for one workspace. Inspect these after uncertain responses.', schema: object({ workspaceId: id.optional(), cursor, limit: page }) },
  operation_read: { method: 'operationRead', title: 'Read a mutation receipt', description: 'Read the recorded outcome of an identified mutation without repeating it.', schema: object({ operationId: id }) },
  job_start: { target: 'jobs', method: 'start', write: true, destructive: true, title: 'Run a native root command on Alpha', description: 'Run exact argv as root on the host, with ordinary networking, persistent home/caches and unrestricted filesystem/service access. Use hostProjectId for its working directory, an absolute cwd for any host directory, or workspaceId plus expectedRevision for a revision-checked workspace. No implicit shell: use bash -lc explicitly when needed. Jobs may run concurrently and survive phone disconnects and backend restarts. Default timeout is 0 (no deadline). Recover the returned job ID with job_status; raw logs remain readable through host_file_read. Retry uncertain submissions with identical inputs and the SAME idempotencyKey.', schema: object({ workspaceId: id.optional(), expectedRevision: revision.optional(), hostProjectId: id.optional(), dataRoot: z.string().min(1).optional(), idempotencyKey: key, label: z.string().max(80).default(''), argv: z.array(z.string()).min(1).describe('Exact command and arguments. No implicit shell or command allowlist. OS and request transport limits apply.'), cwd: z.string().min(1).default('.').describe('Absolute host path or path relative to the attached project/workspace. Defaults to the persistent root job home if neither is supplied.'), network: z.enum(['host', 'none', 'registries']).optional().describe('Native jobs always use ordinary host networking. Legacy none/registries values are accepted as host networking.'), env: z.record(z.string().regex(/^[A-Za-z_][A-Za-z0-9_]*$/), z.string()).default({}).describe('Arbitrary environment overrides; supplied values are persisted with the job request. Prefer reading installed credentials from their files rather than embedding them in arguments.'), timeoutSeconds: z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER).optional().describe('0 or omitted means no deadline on native jobs. Positive seconds set a worker-supervised deadline independent of the backend.'), artifactPaths: z.array(z.string().min(1)).default([]).describe('Optional absolute paths or paths relative to the execution directory to preserve after completion. Native artifacts have no size or count quota.') }) },
  dependency_prepare: { target: 'jobs', method: 'prepareDependencies', write: true, title: 'Preserve installed npm dependencies for deployment', description: 'After installing dependencies and validating the workspace, queue a fixed offline preparation job for its root node_modules and package manifest/lockfile. Read job_status until terminal; success returns preparedDependenciesId and immutable package/lock hashes, image, and Node runtime metadata. Supply that ID when deploying dependency changes. This packages existing modules; it does not install or test them. Refuses missing lockfiles and escaping links. Recover the same job after uncertainty.', schema: object({ workspaceId: id, expectedRevision: revision, idempotencyKey: key, label: z.string().max(80).optional().describe('Optional preparation label; defaults to Prepare deployment dependencies.'), timeoutSeconds: z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER).optional().describe('Optional preparation deadline; 0 means no deadline on native jobs.') }) },
  jobs_list: { target: 'jobs', method: 'list', title: 'Recover coding jobs', description: 'List persisted coding jobs, optionally for a workspace. Completed or interrupted commands are never automatically rerun.', schema: object({ workspaceId: id.optional(), hostProjectId: id.optional(), cursor, limit: page }) },
  job_status: { target: 'jobs', method: 'get', title: 'Read coding job status', description: 'Start here to inspect a job: timestamps, exit status, resulting revision, compact command, recent output, and retention facts. Recent output is an excerpt, not a complete log or parsed test verdict. Request includeCommand only when full argv is needed.', schema: object({ jobId: id, includeCommand: z.boolean().default(false).describe('Default false abbreviates argv to keep status compact. Set true to recover the full saved command arguments.') }) },
  job_logs: { target: 'jobs', method: 'logs', title: 'Read bounded command output', description: 'Read indexed output excerpts with explicit truncation; native jobs also retain complete stdout/stderr and ordered events at the rawLogs paths returned by job_status. Default head preserves ordered output and lifecycle records. Use view=tail to see the newest retained output first, or query/stream to narrow either view. Search covers retained records only. Exhaustive log pagination is usually unnecessary for an outcome already shown by job_status.', schema: object({ jobId: id, cursor: cursor.describe('Omit/0 starts the selected view. Copy nextCursor exactly with the same view and filters. Head pages advance forward. Tail starts newest and pages backward, with records inside each page chronological; its sequence namespace is independent of head. Stop when hasMore=false.'), limit: pageSize('log records', 100, 50), view: z.enum(['head', 'tail']).default('head').describe('Default head reads the original retained log and lifecycle records. Tail reads rolling recent output, newest page first; older jobs may not have a retained tail.'), query: z.string().min(1).max(200).optional().describe('Optional case-sensitive literal substring, 1–200 characters; no regex. Matches only records retained in the selected view, not omitted output.'), stream: z.enum(['stdout', 'stderr', 'system']).optional().describe('Optional exact stream filter; omit for all streams. Lifecycle records use system in the head view.') }) },
  job_cancel: { target: 'jobs', method: 'cancel', write: true, destructive: true, title: 'Cancel a coding job', description: 'Request cancellation of an existing command. The worker records its actual outcome; terminal jobs stay terminal.', schema: object({ jobId: id }) },
  artifact_list: { target: 'jobs', method: 'artifactList', title: 'List preserved job artifacts', description: 'List files copied into protected result storage after the job ended, including sizes and hashes.', schema: object({ jobId: id }) },
  artifact_read: { target: 'jobs', method: 'artifactRead', title: 'Read a preserved artifact', description: 'Read a bounded page of a preserved artifact by its identifier. Source access is authenticated and independent of the original chat. Omit limit for 16384 bytes; copy returned nextCursor.', schema: object({ jobId: id, artifactId: z.string().min(1).max(128).describe('Exact artifact identifier returned by artifact_list; this identifier is not necessarily the content hash.'), cursor, limit: pageSize('artifact bytes', 32768, 16384) }) },
  ...hostTools
};

// Zod messages can contain arbitrary unknown property names. Return only schema
// field names and bounded, value-free issues, never submitted source or values.
export function parseArguments(schema, args) {
  const parsed = schema.safeParse(args);
  if (parsed.success) return parsed.data;
  const fields = new Set([...Object.keys(schema.shape || {}), 'action', 'path', 'expectedSha256', 'content', 'executable', 'oldText', 'newText', 'to']);
  const issues = parsed.error.issues.slice(0, 5).map(issue => {
    const field = issue.path.map(part => typeof part === 'number' && Number.isSafeInteger(part) ? part : fields.has(part) ? part : '<field>').join('.') || '<arguments>';
    const details = issue.code === 'too_small' ? { minimum: issue.minimum } : issue.code === 'too_big' ? { maximum: issue.maximum } : {};
    const message = issue.code === 'too_small' ? `Must be at least ${issue.minimum}.` : issue.code === 'too_big' ? `Must be at most ${issue.maximum}.`
      : issue.code === 'unrecognized_keys' ? 'Contains unsupported fields; use only the advertised arguments.'
        : issue.code === 'invalid_type' ? 'Missing or incorrect argument type.' : issue.code === 'invalid_value' ? 'Value is not one of the advertised options.'
          : issue.code === 'custom' && field === 'maxBytes' ? 'maxBytes and limit must match when both are supplied.'
            : issue.code === 'custom' ? 'Arguments conflict with the documented field constraints.' : 'Value does not match the advertised format.';
    return { field, code: issue.code, message, ...details };
  });
  throw Object.assign(new Error(`Invalid tool arguments: ${issues.map(issue => `${issue.field}: ${issue.message}`).join('; ').slice(0, 500)}`), { code: 'INVALID_ARGUMENT', issues });
}

export function parseCodeCall(action, args) {
  const tool = typeof action === 'string' && Object.hasOwn(codeTools, action) ? codeTools[action] : undefined;
  if (!tool) throw Object.assign(new Error('Unknown coding action'), { code: 'UNKNOWN_ACTION' });
  return { tool, args: parseArguments(tool.schema, args) };
}
